version: 2.26.1
name: aids

services:
  frontend:
    container_name: frontend
    restart: always
    build: ./frontend
    ports:
      - 8080:8080

  backend:
    container_name: backend
    restart: always
    build: ./backend
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=aids
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - REDIS_HOST=redis
      - REDIS_USER=admin
      - REDIS_PASSWORD=admin
    ports:
      - 8000:8000
