version: 2.26.1
name: aids

services:
  frontend:
    container_name: frontend
    restart: always
    build: ./frontend
    ports:
      - 8173:8173


  backend:
    container_name: backend
    restart: always
    build: ./backend
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=aids
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - REDIS_HOST=redis
      - REDIS_USER=admin
      - REDIS_PASSWORD=admin
    depends_on:
      - postgres
      - redis
      - minio
    ports:
      - 8000:8000

  postgres:
    container_name: postgres
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_DB=aids
      - POSTGRES_HOST_AUTH_METHOD=trust

  redis:
    container_name: redis
    restart: always
    image: redis:latest
    environment:
      - REDIS_PASSWORD=admin
  
  minio:
    container_name: minio
    image: minio/minio
    command: server --console-address ":9001" /data/minio/
    ports:
      - 9000:9000
      - 9001:9001
